// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/csat.proto

package csat_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CsatService_NewLike_FullMethodName    = "/csat_api.CsatService/NewLike"
	CsatService_NewMessage_FullMethodName = "/csat_api.CsatService/NewMessage"
	CsatService_NewFriend_FullMethodName  = "/csat_api.CsatService/NewFriend"
	CsatService_TimeSpent_FullMethodName  = "/csat_api.CsatService/TimeSpent"
)

// CsatServiceClient is the client API for CsatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CsatServiceClient interface {
	NewLike(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResponse, error)
	NewMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResponse, error)
	NewFriend(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResponse, error)
	TimeSpent(ctx context.Context, in *RequestWithTime, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type csatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCsatServiceClient(cc grpc.ClientConnInterface) CsatServiceClient {
	return &csatServiceClient{cc}
}

func (c *csatServiceClient) NewLike(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, CsatService_NewLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *csatServiceClient) NewMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, CsatService_NewMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *csatServiceClient) NewFriend(ctx context.Context, in *Request, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, CsatService_NewFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *csatServiceClient) TimeSpent(ctx context.Context, in *RequestWithTime, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, CsatService_TimeSpent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CsatServiceServer is the server API for CsatService service.
// All implementations must embed UnimplementedCsatServiceServer
// for forward compatibility.
type CsatServiceServer interface {
	NewLike(context.Context, *Request) (*EmptyResponse, error)
	NewMessage(context.Context, *Request) (*EmptyResponse, error)
	NewFriend(context.Context, *Request) (*EmptyResponse, error)
	TimeSpent(context.Context, *RequestWithTime) (*EmptyResponse, error)
	mustEmbedUnimplementedCsatServiceServer()
}

// UnimplementedCsatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCsatServiceServer struct{}

func (UnimplementedCsatServiceServer) NewLike(context.Context, *Request) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewLike not implemented")
}
func (UnimplementedCsatServiceServer) NewMessage(context.Context, *Request) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewMessage not implemented")
}
func (UnimplementedCsatServiceServer) NewFriend(context.Context, *Request) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewFriend not implemented")
}
func (UnimplementedCsatServiceServer) TimeSpent(context.Context, *RequestWithTime) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeSpent not implemented")
}
func (UnimplementedCsatServiceServer) mustEmbedUnimplementedCsatServiceServer() {}
func (UnimplementedCsatServiceServer) testEmbeddedByValue()                     {}

// UnsafeCsatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CsatServiceServer will
// result in compilation errors.
type UnsafeCsatServiceServer interface {
	mustEmbedUnimplementedCsatServiceServer()
}

func RegisterCsatServiceServer(s grpc.ServiceRegistrar, srv CsatServiceServer) {
	// If the following call pancis, it indicates UnimplementedCsatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CsatService_ServiceDesc, srv)
}

func _CsatService_NewLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CsatServiceServer).NewLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CsatService_NewLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CsatServiceServer).NewLike(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CsatService_NewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CsatServiceServer).NewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CsatService_NewMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CsatServiceServer).NewMessage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CsatService_NewFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CsatServiceServer).NewFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CsatService_NewFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CsatServiceServer).NewFriend(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CsatService_TimeSpent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWithTime)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CsatServiceServer).TimeSpent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CsatService_TimeSpent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CsatServiceServer).TimeSpent(ctx, req.(*RequestWithTime))
	}
	return interceptor(ctx, in, info, handler)
}

// CsatService_ServiceDesc is the grpc.ServiceDesc for CsatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CsatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "csat_api.CsatService",
	HandlerType: (*CsatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewLike",
			Handler:    _CsatService_NewLike_Handler,
		},
		{
			MethodName: "NewMessage",
			Handler:    _CsatService_NewMessage_Handler,
		},
		{
			MethodName: "NewFriend",
			Handler:    _CsatService_NewFriend_Handler,
		},
		{
			MethodName: "TimeSpent",
			Handler:    _CsatService_TimeSpent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/csat.proto",
}
